AWSTemplateFormatVersion: "2010-09-09"
Description: "Nest Service"

Parameters:
  ServiceName:
    Type: String
  Environment:
    Type: String
  DomainName:
    Type: String
  AuthorizerARN:
    Type: String
  Stage:
    Type: String
    Default: v1
  CertificateARN:
    Type: String
    Default: tester
  DNSZoneName:
    Type: String
  BuildBucket:
    Type: String
  BuildKey:
    Type: String

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['-', [!Ref ServiceName, sqs, !Ref Environment]]

  Dynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: !Join ['-', [!Ref ServiceName, dynamo, !Ref Environment]]

  AuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref ServiceName, authorizerrole, !Ref Environment]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:invokeFunction
                Resource: !Ref AuthorizerARN

  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerCredentials: !GetAtt AuthorizerRole.Arn
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Join ['', ['arn:aws:apigateway:', !Ref 'AWS::Region', ':lambda:path/2015/03/31/functions/', !Ref AuthorizerARN, '/invocations']]
      Type: REQUEST
      IdentitySource: method.request.header.X-Authorization
      Name: !Join ['-', [!Ref ServiceName, authorizer, !Ref Environment]]
      RestApiId: !Ref RestAPI

  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join ['-', [!Ref ServiceName, restapi, !Ref Environment]]
      EndpointConfiguration:
        Types:
          - REGIONAL

  EmptyModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Name: EmptyModel
      RestApiId: !Ref RestAPI
      Schema:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: Empty
        type: object
        properties:
          id:
            type: string

  RestAPIResourceProbe:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: probe

  RestAPIResourceProbeGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref RestAPIResourceProbe
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: GET
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: |
            {"statusCode": 200}
        IntegrationResponses:
          - StatusCode: 200
        ResponseTemplates:
          application/json: |
            {}
        MethodResponses:
          - StatusCode: 200

  RestAPIBug:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: bug

  RestAPIBugPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref RestAPIBug
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: POST
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: !Ref EmptyModel
        - StatusCode: 502
          ResponseModels:
            application/json: !Ref EmptyModel
        - StatusCode: 400
          ResponseModels:
            application/json: !Ref EmptyModel
      Integration:
        Type: AWS_PROXY
        Uri: !Join ['', ['arn:aws:apigateway:', !Ref 'AWS::Region', ':lambda:path/2015-03-31/functions/', !GetAtt Service.Arn, '/invocations']]
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
          - StatusCode: 502
          - StatusCode: 400

  RestAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: RestAPIResourceProbeGet
    Properties:
      RestApiId: !Ref RestAPI
      StageName: !Ref Stage

  RestAPIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      CertificateArn: !Ref CertificateARN

  RestAPIDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref Stage
      DomainName: !Ref RestAPIDomainName
      RestApiId: !Ref RestAPI
      Stage: !Ref Stage

  PrimaryRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneName: !Ref DNSZoneName
      Weight: 1
      SetIdentifier: !Join ['-', [!Ref ServiceName, recordset, !Ref Environment, !Ref 'AWS::Region']]
      AliasTarget:
        HostedZoneId: !GetAtt RestAPIDomainName.RegionalHostedZoneId
        DNSName: !GetAtt RestAPIDomainName.RegionalDomainName
        EvaluateTargetHealth: false

  ServiceARN:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref ServiceName, role, !Ref Environment]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action: dynamodb:*
                Resource: !GetAtt Dynamo.Arn
              - Effect: Allow
                Resource: '*'
                Action:
                  - dynamodb:DescribeReservedCapacityOfferings
                  - dynamodb:ListGlobalTables
                  - dynamodb:ListTables
                  - dynamodb:DescribeReservedCapacity
                  - dynamodb:ListBackups
                  - dynamodb:PurchaseReservedCapacityOfferings
                  - dynamodb:DescribeLimits
                  - dynamodb:ListStreams

  Service:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join ['-', [!Ref ServiceName, lambda, !Ref Environment]]
      Role: !GetAtt ServiceARN.Arn
      Runtime: go1.x
      Handler: !Ref ServiceName
      Timeout: 10
      Environment:
        Variables:
          DB_TABLE: !Join ['-', [!Ref ServiceName, dynamo, !Ref Environment]]
#          DB_TABLE: !Ref Dynamo
          DB_ENDPOINT: !Join ['', ['http://', 'dynamodb.', !Ref 'AWS::Region', '.amazonaws.com']]
          DB_REGION: !Ref AWS::Region
      Code:
        S3Bucket: !Ref BuildBucket
        S3Key: !Ref BuildKey

  ServiceInvokeBug:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Service.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ['', ['arn:aws:execute-api:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref RestAPI, '/*/POST/bug']]

